<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronics</name>
   <tag></tag>
   <elementGuidId>78a1fbe2-b975-4770-8329-33590875d2c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Electronics')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9278e785-8e7f-4723-83df-e0f893d22bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>product-category.php?id=4&amp;type=top-category</value>
      <webElementGuid>3feb2cd4-feb0-4ae6-a12a-83863dddac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electronics</value>
      <webElementGuid>fd6a123a-8100-47b1-b1e1-c77615ebdeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/div[@class=&quot;nav&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 pl_0 pr_0&quot;]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;menu&quot;]/ul[1]/li[@class=&quot;menu-dropdown-icon&quot;]/a[1]</value>
      <webElementGuid>c791de25-3979-4c4a-ad18-627f035b2299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electronics')]</value>
      <webElementGuid>2efa7caf-49da-4968-91f9-9d60f1c67b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Girls'])[3]/following::a[1]</value>
      <webElementGuid>42c0b831-e979-4bce-a801-7e7db9b5219e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boys'])[3]/following::a[2]</value>
      <webElementGuid>3c4aa027-605c-42df-8c95-25a29fa35a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronic Items'])[1]/preceding::a[1]</value>
      <webElementGuid>1e152f3d-3d40-4160-b736-d9c2dcbe9e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cell Phone and Accessories'])[1]/preceding::a[2]</value>
      <webElementGuid>df0356da-9ea7-4754-a7c5-aaf98829f1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Electronics']/parent::*</value>
      <webElementGuid>e9966550-6ed8-47ab-a836-60317b45b38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'product-category.php?id=4&amp;type=top-category')]</value>
      <webElementGuid>e70d5645-6bd4-4ceb-84ae-2cc4922dd311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>e8d7b93a-ea86-475c-a50c-4618a9a0b027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'product-category.php?id=4&amp;type=top-category' and (text() = 'Electronics' or . = 'Electronics')]</value>
      <webElementGuid>b54a014d-c440-4a0e-b466-274fe2c887c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
