<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Vietnam</name>
   <tag></tag>
   <elementGuidId>bf0b1e4d-cb6d-448b-abd4-5948fd067daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cust_country-nl-result-wsht-237</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-cust_country-nl-result-wsht-237']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8cd28328-10eb-40fb-aad6-bf203afea529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>58f86150-9ef2-4ebd-adbb-051a8b46c368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cust_country-nl-result-wsht-237</value>
      <webElementGuid>c30877d3-719b-4124-a3e2-cdc884fede22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>51bfa463-277b-4730-88a6-8210812f7967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f25be63f-1f16-4c1b-a2bb-1263ef20c319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vietnam</value>
      <webElementGuid>03910f84-688f-4fb0-9b2d-802935372f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cust_country-nl-result-wsht-237&quot;)</value>
      <webElementGuid>b1508bed-092f-493a-8166-88f566f2db5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-cust_country-nl-result-wsht-237']</value>
      <webElementGuid>41db4d2f-a610-4aa6-a119-92a19e3b9d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-cust_country-nl-results']/li</value>
      <webElementGuid>b64b6517-45f7-4fd7-94b0-8a141cb02294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[2]/following::li[1]</value>
      <webElementGuid>6c2dd464-9e34-4b0d-b172-acbac4a7ade5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::li[1]</value>
      <webElementGuid>c407bf36-5a2a-4038-9e0d-881047faa76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li</value>
      <webElementGuid>406eb1fd-e04e-4701-b0a6-0793c8c961e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-cust_country-nl-result-wsht-237' and (text() = 'Vietnam' or . = 'Vietnam')]</value>
      <webElementGuid>52c20133-5901-4879-8c9d-3bfc4d7a25d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
