<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_country</name>
   <tag></tag>
   <elementGuidId>32d95e14-c42e-4ac0-82c7-fdbf31ac9b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cust_country-j4-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-cust_country-j4-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aebeb5c1-a6c2-4d8e-a6b8-015536ca0cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>6bfd5358-300a-4fbb-a35e-14d431c400bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cust_country-j4-container</value>
      <webElementGuid>64567c9d-f43a-4edf-b0ac-bbab0507334a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select country</value>
      <webElementGuid>ebd774dd-97a9-4c55-b3e2-a160b0e3fe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select country</value>
      <webElementGuid>02077b98-f37f-4d99-bdb6-0c1b58f2918e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cust_country-j4-container&quot;)</value>
      <webElementGuid>bfe346b4-6941-45b3-859a-52d9f3fd3fb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-cust_country-j4-container']</value>
      <webElementGuid>8062fea8-4bae-402e-9a36-7ebf5106fb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country *'])[1]/following::span[4]</value>
      <webElementGuid>50080963-1d26-41c5-9f30-b05ab2647a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address *'])[1]/following::span[4]</value>
      <webElementGuid>1daf7f24-56aa-409a-9e71-e266e775a27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City *'])[1]/preceding::span[3]</value>
      <webElementGuid>f3db3e42-cb79-441a-9d12-f8d122ef2cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State *'])[1]/preceding::span[3]</value>
      <webElementGuid>f093bb3a-c979-450e-933b-1d4a1e813839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>80ee3459-ebf1-42e2-bb89-342510a824ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-cust_country-j4-container' and @title = 'Select country' and (text() = 'Select country' or . = 'Select country')]</value>
      <webElementGuid>331f17ad-a3ef-4cc5-880e-1838a0ec637a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
