<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select_country</name>
   <tag></tag>
   <elementGuidId>024110b7-2d1e-46fb-818a-7a6243da1fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-cust_country-k5-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-cust_country-k5-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65bf0823-aaa3-44f1-9ddf-d58a56b4f719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>637472a9-e793-40dd-b905-f01d06951880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-cust_country-k5-container</value>
      <webElementGuid>35a18ba1-2b30-4b99-9635-e356dc90fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select country</value>
      <webElementGuid>28debe73-6bc3-47c6-b5bd-27328a39a217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select country</value>
      <webElementGuid>1057057d-8637-40c7-989c-b0798c5bcd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-cust_country-k5-container&quot;)</value>
      <webElementGuid>a13fbf55-be2f-4b2b-a1a7-cda64bf192ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-cust_country-k5-container']</value>
      <webElementGuid>095b9dc6-a6e4-4581-81cf-c0a3e6c3d79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country *'])[1]/following::span[4]</value>
      <webElementGuid>0332b90b-f768-447f-b85f-471fc6a05d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address *'])[1]/following::span[4]</value>
      <webElementGuid>8ace2497-3741-42c0-9e84-9d71903b68cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City *'])[1]/preceding::span[3]</value>
      <webElementGuid>6369913f-d22e-4d75-8d3e-37cb2864fcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State *'])[1]/preceding::span[3]</value>
      <webElementGuid>c24413a3-fa21-49c1-ba4e-eec6cf9fd031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>b3025f0c-d681-47ab-b05f-cc2ac6d8b8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-cust_country-k5-container' and @title = 'Select country' and (text() = 'Select country' or . = 'Select country')]</value>
      <webElementGuid>3e2cc841-0ca8-4cc7-a69d-86a587d22b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
